In [190]:
#L2HW(Game 2)
def get_user1_input(remaining_round):
    while True:
        player1_input_vert_str = input("Player1, please enter 0-2 in the vertical direction:(remaining round:{})".format(remaining_round))
        player1_input_hort_str = input("Player1, please enter 0-2 in the horizontal direction:,(remaining round:{})".format(remaining_round))
        if player1_input_vert_str.isdigit():
            player1_input_vert_int = int(player1_input_vert_str)
        if player1_input_hort_str.isdigit():
            player1_input_hort_int = int(player1_input_hort_str)
            if (player1_input_vert_int >= 0 and player1_input_vert_int <= 2) and (player1_input_hort_int >= 0 and player1_input_hort_int <= 2):
                gameboard[(player1_input_vert_int,player1_input_hort_int)] = player1
                print(gameboard)
#                 if (player1_input_vert_int,player1_input_hort_int) != (player2_input_vert_int,player2_input_hort_int)
                return(player1_input_vert_int,player1_input_hort_int)
            else:
                print('Please input an integer in a vaild range')
                continue

In [191]:
def get_user2_input(remaining_round):
    while True:
        player2_input_vert_str = input("Player2, please enter 0-2 in the vertical direction:,(remaining round:{})".format(remaining_round))
        player2_input_hort_str = input("Player2, please enter 0-2 in the horizontal direction:,(remaining round:{})".format(remaining_round))
        if player2_input_vert_str.isdigit():
            player2_input_vert_int = int(player2_input_vert_str)
        if player2_input_hort_str.isdigit():
            player2_input_hort_int = int(player2_input_hort_str)
            if (player2_input_vert_int >= 0 and player2_input_vert_int <= 2) and (player2_input_hort_int >= 0 and player2_input_hort_int <= 2):
                gameboard[(player2_input_vert_int,player2_input_hort_int)] = player2
                print(gameboard)
#                 if (player1_input_vert_int,player1_input_hort_int) != (player2_input_vert_int,player2_input_hort_int):
                return(player2_input_vert_int,player2_input_hort_int)
            else:
                print('Please input an integer in a vaild range')
                continue

In [192]:
def check_ans_player1():
    #case1: X case
    if (a + e + i) or (c+ e +g) == 3:
        player1_isWin = True
    #case2: cross case
    elif (b + e + h) or (d + e + f) == 3:
        player1_isWin = True
    #case3: row and column case
    elif (a + b + c) or (a + d + g) or (g + h + i) or (c + f + i) == 3:
        player1_isWin = True
    else:
        player1_isWin = False
    return(player1_isWin)

In [193]:
def check_ans_player2():
    #case1: X case
    if (a + e + i) or (c+ e +g) == 6:
        player2_isWin = True
    #case2: cross case
    elif (b + e + h) or (d + e + f) == 6:
        player2_isWin = True
    #case3: row and column case
    elif (a + b + c) or (a + d + g) or (g + h + i) or (c + f + i) == 6:
        player2_isWin = True
    else:
        player2_isWin = False
    return(player2_isWin)

In [195]:
#Assumptions
import numpy as np
k = 3
m = 5
gameboard = np.zeros((k,k))
player1 = 1
player2 = 2
a = gameboard[(0,0)]
b = gameboard[(0,1)]
c = gameboard[(0,2)]
d = gameboard[(1,0)]
e = gameboard[(1,1)]
f = gameboard[(1,2)]
g = gameboard[(2,0)]
h = gameboard[(2,1)]
i = gameboard[(2,2)]
for i in range(m):
    #move 1: save location of player1
    player1_input_vert, player1_input_hort = get_user1_input(m-i)
    #move 2: save location of player2, continute until move 9
    player2_input_vert, player2_input_hort = get_user2_input(m-i)
    if i == 0 or 2:
        player1_isWin = check_ans_player1()
        if player1_isWin:
            print('Player1 win~~~')
            break
    elif i == 1:
        player2_isWin = check_ans_player2()
        if player2_isWin:
            print('Player2 win~~~')
            break
else:
    print('-------Draw-------')

Player1, please enter 0-2 in the vertical direction:(remaining round:5) 0
Player1, please enter 0-2 in the horizontal direction:,(remaining round:5) 0


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Player2, please enter 0-2 in the vertical direction:,(remaining round:5) 2
Player2, please enter 0-2 in the horizontal direction:,(remaining round:5) 1


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 2. 0.]]


Player1, please enter 0-2 in the vertical direction:(remaining round:4) 1
Player1, please enter 0-2 in the horizontal direction:,(remaining round:4) 1


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 0.]]


Player2, please enter 0-2 in the vertical direction:,(remaining round:4) 2
Player2, please enter 0-2 in the horizontal direction:,(remaining round:4) 0


[[1. 0. 0.]
 [0. 1. 0.]
 [2. 2. 0.]]
Player1 win~~~
